services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP (ACME http-01)
      - "443:443"   # HTTPS
    volumes:
      - ./conf:/etc/caddy    # your Caddy config
      - ./site:/srv          # serve static files from here
      - caddy_data:/data     # certs, logs, etc (persisted)
      - caddy_config:/config # caddy internal config
    environment:
      - UPSTREAM_API_GATEWAY=api-gateway-blue
      - UPSTREAM_WORKER=worker-blue
    depends_on:
      - api-gateway-blue
      - api-gateway-green
      - worker-blue
      - worker-green
    networks:
      - web
  api-gateway-blue:
    image: ghcr.io/villetostream/villeto-monolith/api-gateway:blue
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: builder
    container_name: api-gateway-blue
    restart: always
    depends_on:
      - worker-blue
      - worker-green
    command: pnpm run start api-gateway
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    networks:
      - web

  api-gateway-green:
    image: ghcr.io/villetostream/villeto-monolith/api-gateway:green
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: builder
    container_name: api-gateway-green
    ports:
      - '3001:3000'
    depends_on:
      - worker-blue
      - worker-green
    command: pnpm run start api-gateway
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    networks:
      - web

  worker-blue:
    image: ghcr.io/villetostream/villeto-monolith/worker:blue
    build: 
      context: .
      dockerfile: ./apps/worker/Dockerfile
      target: builder
    container_name: worker-blue
    command: pnpm run start worker
    ports:
      - '3002:3001'
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    networks:
      - web

  worker-green:
    image: ghcr.io/villetostream/villeto-monolith/worker:green
    build: 
      context: .
      dockerfile: ./apps/worker/Dockerfile
      target: builder
    container_name: worker-green
    command: pnpm run start worker
    ports:
      - '3003:3001'
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge
